version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - apt-get update
      - apt-get install -y curl
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
      - apt-get update && apt-get install -y yarn
      - yarn install

   build:
    commands:
      - yarn install
      - yarn build
      - next export

artifacts:
  files:
    - '**/*'
