version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16.x
    commands:
      - yarn install

  pre_build:
    commands:
      - yarn build

  build:
    commands:
      - echo Build started on `date`
      - yarn export

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  base-directory: 'out'
