import Head from 'next/head'
import PrelaunchHomePage from '../components/PrelaunchHomePage/PrelaunchHomePage'

export default function Home() {
  return (
    <>
      <Head>
        <title>ActingAccents.com</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <PrelaunchHomePage />
      </main>
    </>
  )
}
