import Head from 'next/head'

import styles from '../styles/Home.module.css'
import PrelaunchHomePage from './PrelaunchHomePage/PrelaunchHomePage'
import Layout from './_layout'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Layout>
          <PrelaunchHomePage /> 
        </Layout>
      </main>
    </>
  )
}
